title: Andrew Larson
description: I am a current student at Lawrence University majoring in Economics and minoring in Data Science. I am also a member of the Lawrence University Mens Tennis Team and the Data Science CLub.
remote_theme: pages-themes/minimal@v0.2.0
plugsins:
- jekyll-remote-theme
